name: Test libtcod plumbing
on: 
  workflow_dispatch:
jobs: 
  msys2:
    runs-on: windows-2022
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS  
          location: D:\
          release: false
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
      - shell: msys2 {0}  
        run: |
          set MSYSTEM=MINGW64
          g++ -version
