name: Test libtcod plumbing
on: 
  workflow_dispatch:
jobs: 
  msys2:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}    
    steps:
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          location: D:\
          release: false
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
      -  name: Check if g++ installed
         run: |
          g++ --version
